# alpha 0.1 Retrieval System Configuration

# Model configuration
model_name: "/path/to/your/local/cosmos-model"
device: "cuda"  # Use "cpu" if CUDA is not available
batch_size: 4   # Number of videos to process in parallel
num_frames: 8   # Number of frames to extract per video
# Unified paths (single source of truth)
embeddings_path: "data/unified_embeddings.parquet"  # All video embeddings (database + query)
input_path: "data/unified_input_path.parquet"       # All video file paths
use_safe_serialization: true
supported_formats: [".mp4", ".avi", ".mov", ".mkv", ".webm"]
thumbnail_size: [480, 270]  # 16:9 aspect ratio, higher resolution
default_top_k: 5              # Default number of results to return
similarity_threshold: 0.0     # Minimum similarity score (0-1)
default_clip_duration: 20     # Default clip duration in seconds when span_end cannot be determined
enable_caching: true
cache_size: 1000
log_level: "INFO"
log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
