# ALFA 0.1 Retrieval System Configuration

# Model configuration
model_name: "/path/to/your/local/cosmos-model"
device: "cuda"  # Use "cpu" if CUDA is not available
batch_size: 4   # Number of videos to process in parallel
num_frames: 8   # Number of frames to extract per video
main_embeddings_path: "data/main_embeddings.parquet"      # Main database (reference videos embeddings)
query_embeddings_path: "data/query_embeddings.parquet"    # Query database (user input videos embeddings)
main_input_path: "data/main_input_path.parquet"             # Main video file paths
query_input_path: "data/query_input_path.parquet"           # Query video file paths
use_safe_serialization: true
supported_formats: [".mp4", ".avi", ".mov", ".mkv", ".webm"]
thumbnail_size: [480, 270]  # 16:9 aspect ratio, higher resolution
default_top_k: 5              # Default number of results to return
similarity_threshold: 0.0     # Minimum similarity score (0-1)
enable_caching: true
cache_size: 1000
log_level: "INFO"
log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
